# サイドバー

- label: めにゅー
  items:
    - label: 'TOPページ'
      link: '/'
    - label: '入り方'
      link: '/join'
    - label: 'ルール/利用規約'
      link: '/terms'
- label: しょうさい
  items:
    - label: '運営一覧'
      link: '/staff'
    - label: 'よくある質問'
      link: '/faq'

# 外部リンク

- label: リンク一覧
  items:
    - label: 'Discord'
      link: https://discord.gg/Xd2df44

- label: 使用/ご協力
  items:
    - label: 'さくらのVPS 様'
      link: https://vps.sakura.ad.jp/
