# サイドバー

- label: はじめに
  items:
    - label: 'ようこそ'
      link: '/'
    - label: '入り方'
      link: '/join'
    - label: 'ルール'
      link: '/terms'
- label: もっと詳しく
  items:
    - label: '運営一覧'
      link: '/staff'
    - label: 'よくある質問'
      link: '/faq'
    - label: '内部アドレス'
      link: '/address'

# 外部リンク

- label: 外部リンク
  items:
    - label: '🔗 Linktree'
      link: https://linktr.ee/azisaba
    - label: '💸 寄付'
      link: https://store.azisaba.net
    - label: '✅ ステータス'
      link: https://status.azisaba.net
    - label: '📥 リソースパック'
      link: https://packs.azisaba.net
- label: 協力と提携
  items:
    - label: 'DDPS 様'
      link: https://ddps.jp
    - label: 'ちゃぶだいさ～ば～ 様'
      link: https://chabudai.xyz
    - label: 'Strife 様'
      link: https://twitter.com/STRIFE_mcserver
    - label: 'Coretol 様'
      link: https://matchatb.wixsite.com/coretol
