# Sidebar navigation

- label: 'ようこそ'
  link: '/'
- label: '入り方'
  link: '/join'
- label: 'ルール'
  link: '/terms'
- label: さらに
  items:
    - label: 'よくある質問'
      link: '/faq'
    - label: '内部アドレス'
      link: '/address'
- label: コミュニティー
  items:
    - label: 'Discord'
      link: https://discord.gg/seheC2W
    - label: 'Twitter'
      link: https://twitter.com/AzisabaNetwork
    - label: 'YouTube'
      link: https://www.youtube.com/channel/UCHkH9_MKql1MFi0MZ_tqQbg
    - label: 'GitHub'
      link: https://github.com/azisaba
- label: 投票
  items:
    - label: 'Japan Minecraft Servers'
      link: https://minecraft.jp/servers/59b7c551a9b0bd23dc00834d
    - label: 'monocraft'
      link: https://monocraft.net/servers/xWBVrf1nqB2P0LxlMm2v
- label: その他
  items:
    - label: '寄付'
      link: https://store.azisaba.net
    - label: 'ステータス'
      link: https://status.azisaba.net
    - label: 'リソースパック'
      link: https://packs.azisaba.net
