name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: パッケージのインストール
        run: yarn install

      - name: Gatsbyコマンドのインストール
        run: |
          echo "$(yarn global bin)" >> $GITHUB_PATH
          yarn global add gatsby-cli

      - name: Gatsbyビルドの実行
        run: gatsby build

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: public

  deploy:
    name: デプロイ
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: site
          path: public

      - name: デプロイの実行
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: azisaba.net
